In [14]:
import pandas as pd
df = pd.read_csv('Calls.csv')

display(df.head(n=10))

,DateTime,City,Facility,Device,Desk,Operator,WaitTime,ConversationTime,Reason,ReasonEnteredByUser,Flag_BarrierOpened
0,2023-07-15 06:02:52.727,Eindhoven,Eindhoven Veemgebouw,EI/VE/IN ABBO,9926,Qais Shirzai,02:05:34.870000,00:00:02.040000,No reason entered,-,-
1,2023-07-15 06:05:15.100,Breda,Breda De Prins,BR/DP/UIT-2,9926,Qais Shirzai,02:03:16.037000,00:00:01.633000,No reason entered,-,-
2,2023-07-15 06:10:21.567,Breda,Breda De Prins,BR/DP/BA-1,9926,Qais Shirzai,01:58:14.226000,00:00:01.030000,No reason entered,-,-
3,2023-07-15 06:10:19.817,Breda,Breda De Prins,BR/DP/BA-3,9926,Qais Shirzai,01:58:14.013000,00:00:01,No reason entered,-,-
4,2023-07-15 06:13:13.130,Breda,Breda De Prins,BR/DP/DL-2,9926,Qais Shirzai,01:55:24.383000,00:00:01.380000,No reason entered,-,-
5,2023-07-15 06:24:28.147,Breda,Breda De Prins,BR/DP/BA-2,9926,Qais Shirzai,01:44:11.400000,00:00:00.623000,No reason entered,-,-
6,2023-07-15 06:26:43.303,Breda,Breda De Prins,BR/DP/UIT-1,9926,Qais Shirzai,01:43:09.150000,00:00:00.407000,No reason entered,-,-
7,2023-07-15 06:39:07.153,Breda,Breda De Prins,BR/DP/DL-3,9926,Qais Shirzai,01:30:46.677000,00:00:01.306000,No reason entered,-,-
8,2023-01-28 20:19:58.127,Tilburg,Tilburg Pieter Vredeplein,TI/PV Inrit 2,-,-,01:29:08.363000,-,-,-,-
9,2023-01-28 20:23:31.847,Tilburg,Tilburg Pieter Vredeplein,TI/PV Inrit 1,-,-,01:25:36.650000,-,-,-,-

In [2]:
df = df.replace('-', 0)
print(display(df['City'].unique()))
  
print(df.isna().count())

print(df.info())

array(['Eindhoven', 'Breda', 'Tilburg', 'Veldhoven', 'Leiden',
       'Rotterdam', 'Valkenburg', 'Alkmaar', 'Roermond', 'Maastricht',
       'Almere', 'Hengelo', 'Deventer', 'IJsselstein', 'Zaandam',
       'Amstelveen', 'Amsterdam', 'Den Helder', 'Arnhem', 'Oosterhout',
       'Den Haag', 'Delft', 'Weert', 'Purmerend', 'Amersfoort', 'Hoorn',
       'Nijmegen', 'Katwijk', 'Hoofddorp', 'Assen', 'Pijnacker', 'Venray',
       'Utrecht', 'Bussum', 'Nootdorp', 0, 'Veenendaal'], dtype=object)

None
DateTime               433974
City                   433974
Facility               433974
Device                 433974
Desk                   433974
Operator               433974
WaitTime               433974
ConversationTime       433974
Reason                 433974
ReasonEnteredByUser    433974
Flag_BarrierOpened     433974
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433974 entries, 0 to 433973
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   DateTime             433974 non-null  object
 1   City                 433974 non-null  object
 2   Facility             433974 non-null  object
 3   Device               433974 non-null  object
 4   Desk                 433974 non-null  object
 5   Operator             433974 non-null  object
 6   WaitTime             433974 non-null  object
 7   ConversationTime     433974 non-null  object
 8   Reason               433974 non-null  object
 9   ReasonEnteredByUser  433974 non-null  object
 10  Flag_BarrierOpened   433974 non-null  object
dtypes: object(11)
memory usage: 36.4+ MB
None

In [3]:
cities= df[df['City']!=0]

#print(cities['City'].unique())
sort_cities = sorted(cities['City'].unique())
print(sort_cities)

['Alkmaar', 'Almere', 'Amersfoort', 'Amstelveen', 'Amsterdam', 'Arnhem', 'Assen', 'Breda', 'Bussum', 'Delft', 'Den Haag', 'Den Helder', 'Deventer', 'Eindhoven', 'Hengelo', 'Hoofddorp', 'Hoorn', 'IJsselstein', 'Katwijk', 'Leiden', 'Maastricht', 'Nijmegen', 'Nootdorp', 'Oosterhout', 'Pijnacker', 'Purmerend', 'Roermond', 'Rotterdam', 'Tilburg', 'Utrecht', 'Valkenburg', 'Veenendaal', 'Veldhoven', 'Venray', 'Weert', 'Zaandam']

In [4]:
df_0 = df[df['ConversationTime']==0]
df_0

,DateTime,City,Facility,Device,Desk,Operator,WaitTime,ConversationTime,Reason,ReasonEnteredByUser,Flag_BarrierOpened
8,2023-01-28 20:19:58.127,Tilburg,Tilburg Pieter Vredeplein,TI/PV Inrit 2,0,0,01:29:08.363000,0,0,0,0
9,2023-01-28 20:23:31.847,Tilburg,Tilburg Pieter Vredeplein,TI/PV Inrit 1,0,0,01:25:36.650000,0,0,0,0
11,2023-01-28 20:40:28.187,Tilburg,Tilburg Emma passage,TI/EP Betaalautomaat 4 Cashless,0,0,01:08:41.890000,0,0,0,0
12,2022-10-23 05:04:03.723,Tilburg,Tilburg Pieter Vredeplein,TI/PV Loopdeur lift,0,0,00:57:14.874000,0,0,0,0
13,2023-01-28 20:56:26.053,Tilburg,Tilburg Emma passage,TI/EP Betaalautomaat 1 Fullservice,0,0,00:52:57.024000,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
433969,2022-11-27 11:38:34.457,0,0,VB/AK/UIT-1,0,0,0,0,0,0,1
433970,2023-09-28 17:45:21.910,0,0,VB/AK/UIT-2,0,0,0,0,0,0,1
433971,2023-09-28 20:16:15.523,0,0,VB/AK/UIT-2,0,0,0,0,0,0,1
433972,2023-06-03 11:44:34.517,0,0,WE/UR/DL,0,0,0,0,0,0,1
433973,2023-06-29 14:14:42.440,0,0,ZA/EB/UIT-1 NP,0,0,0,0,0,0,0

In [15]:
df

,DateTime,City,Facility,Device,Desk,Operator,WaitTime,ConversationTime,Reason,ReasonEnteredByUser,Flag_BarrierOpened
0,2023-07-15 06:02:52.727,Eindhoven,Eindhoven Veemgebouw,EI/VE/IN ABBO,9926,Qais Shirzai,02:05:34.870000,00:00:02.040000,No reason entered,-,-
1,2023-07-15 06:05:15.100,Breda,Breda De Prins,BR/DP/UIT-2,9926,Qais Shirzai,02:03:16.037000,00:00:01.633000,No reason entered,-,-
2,2023-07-15 06:10:21.567,Breda,Breda De Prins,BR/DP/BA-1,9926,Qais Shirzai,01:58:14.226000,00:00:01.030000,No reason entered,-,-
3,2023-07-15 06:10:19.817,Breda,Breda De Prins,BR/DP/BA-3,9926,Qais Shirzai,01:58:14.013000,00:00:01,No reason entered,-,-
4,2023-07-15 06:13:13.130,Breda,Breda De Prins,BR/DP/DL-2,9926,Qais Shirzai,01:55:24.383000,00:00:01.380000,No reason entered,-,-
...,...,...,...,...,...,...,...,...,...,...,...
433969,2022-11-27 11:38:34.457,-,-,VB/AK/UIT-1,-,-,-,-,-,-,1
433970,2023-09-28 17:45:21.910,-,-,VB/AK/UIT-2,-,-,-,-,-,-,1
433971,2023-09-28 20:16:15.523,-,-,VB/AK/UIT-2,-,-,-,-,-,-,1
433972,2023-06-03 11:44:34.517,-,-,WE/UR/DL,-,-,-,-,-,-,1
433973,2023-06-29 14:14:42.440,-,-,ZA/EB/UIT-1 NP,-,-,-,-,-,-,-

In [6]:
#df['Device_1'] = df['Device'].str.split('/').str[2]

#df = df.drop('Device', axis=1)
#df

In [7]:
df

,DateTime,City,Facility,Device,Desk,Operator,WaitTime,ConversationTime,Reason,ReasonEnteredByUser,Flag_BarrierOpened
0,2023-07-15 06:02:52.727,Eindhoven,Eindhoven Veemgebouw,EI/VE/IN ABBO,9926,Qais Shirzai,02:05:34.870000,00:00:02.040000,No reason entered,0,0
1,2023-07-15 06:05:15.100,Breda,Breda De Prins,BR/DP/UIT-2,9926,Qais Shirzai,02:03:16.037000,00:00:01.633000,No reason entered,0,0
2,2023-07-15 06:10:21.567,Breda,Breda De Prins,BR/DP/BA-1,9926,Qais Shirzai,01:58:14.226000,00:00:01.030000,No reason entered,0,0
3,2023-07-15 06:10:19.817,Breda,Breda De Prins,BR/DP/BA-3,9926,Qais Shirzai,01:58:14.013000,00:00:01,No reason entered,0,0
4,2023-07-15 06:13:13.130,Breda,Breda De Prins,BR/DP/DL-2,9926,Qais Shirzai,01:55:24.383000,00:00:01.380000,No reason entered,0,0
...,...,...,...,...,...,...,...,...,...,...,...
433969,2022-11-27 11:38:34.457,0,0,VB/AK/UIT-1,0,0,0,0,0,0,1
433970,2023-09-28 17:45:21.910,0,0,VB/AK/UIT-2,0,0,0,0,0,0,1
433971,2023-09-28 20:16:15.523,0,0,VB/AK/UIT-2,0,0,0,0,0,0,1
433972,2023-06-03 11:44:34.517,0,0,WE/UR/DL,0,0,0,0,0,0,1
433973,2023-06-29 14:14:42.440,0,0,ZA/EB/UIT-1 NP,0,0,0,0,0,0,0

In [16]:
df['WaitTime'] = pd.to_timedelta(df['WaitTime'], errors = 'coerce')
df['WaitTimeSeconds'] = df['WaitTime'].dt.total_seconds()
df['Convo_Time'] = pd.to_timedelta(df['ConversationTime'], errors = 'coerce')
df['convoTimeSeconds'] = df['ConversationTime'].dt.total_seconds()
df

AttributeError: Can only use .dt accessor with datetimelike values

In [17]:
dict_2= {
 'Alkmaar': 'Noord-Holland',
 'Almere': 'Flevoland',
 'Amersfoort': 'Utrecht',
 'Amstelveen': 'Noord-Holland',
 'Amsterdam': 'Noord-Holland',
 'Arnhem': 'Gelderland',
 'Assen': 'Drenthe',
 'Breda': 'Noord-Brabant',
 'Bussum': 'Noord-Holland',
 'Deventer': 'Overijssel',
 'Delft': 'Zuid-Holland',
 'Den Haag': 'Zuid-Holland',
 'Den Helder': 'Noord-Holland',
 'Eindhoven': 'Noord-Brabant',
 'Hengelo': 'Overijssel',
 'Hoofddorp': 'Noord-Holland',
 'Hoorn': 'Noord-Holland',
 'IJsselstein': 'Utrecht',
 'Katwijk': 'Zuid-Holland',
 'Leiden': 'Zuid-Holland',
 'Maastricht': 'Limburg',
 'Nijmegen': 'Gelderland',
 'Nootdorp': 'Zuid-Holland',
 'Oosterhout': 'Noord-Brabant',
 'Pijnacker': 'Zuid-Holland',
 'Purmerend': 'Noord-Holland',
 'Roermond': 'Limburg',
 'Rotterdam': 'Zuid-Holland',
 'Tilburg': 'Noord-Brabant',
 'Utrecht': 'Utrecht',
 'Valkenburg': 'Limburg',
 'Veenendaal': 'Utrecht',
 'Veldhoven': 'Noord-Brabant',
 'Venray': 'Limburg',
 'Weert': 'Limburg',
 'Zaandam': 'Noord-Holland'
}

In [18]:
dict_2

{'Alkmaar': 'Noord-Holland',
 'Almere': 'Flevoland',
 'Amersfoort': 'Utrecht',
 'Amstelveen': 'Noord-Holland',
 'Amsterdam': 'Noord-Holland',
 'Arnhem': 'Gelderland',
 'Assen': 'Drenthe',
 'Breda': 'Noord-Brabant',
 'Bussum': 'Noord-Holland',
 'Deventer': 'Overijssel',
 'Delft': 'Zuid-Holland',
 'Den Haag': 'Zuid-Holland',
 'Den Helder': 'Noord-Holland',
 'Eindhoven': 'Noord-Brabant',
 'Hengelo': 'Overijssel',
 'Hoofddorp': 'Noord-Holland',
 'Hoorn': 'Noord-Holland',
 'IJsselstein': 'Utrecht',
 'Katwijk': 'Zuid-Holland',
 'Leiden': 'Zuid-Holland',
 'Maastricht': 'Limburg',
 'Nijmegen': 'Gelderland',
 'Nootdorp': 'Zuid-Holland',
 'Oosterhout': 'Noord-Brabant',
 'Pijnacker': 'Zuid-Holland',
 'Purmerend': 'Noord-Holland',
 'Roermond': 'Limburg',
 'Rotterdam': 'Zuid-Holland',
 'Tilburg': 'Noord-Brabant',
 'Utrecht': 'Utrecht',
 'Valkenburg': 'Limburg',
 'Veenendaal': 'Utrecht',
 'Veldhoven': 'Noord-Brabant',
 'Venray': 'Limburg',
 'Weert': 'Limburg',
 'Zaandam': 'Noord-Holland'}

In [19]:
region_names = []

# Iterate over each row in the dataframe
for index, row in df.iterrows():
    city = row['City']
    # Find the corresponding region name in the dictionary
    region_name = dict_2.get(city, None)  # Returns None if not found
    # Append the region name to the list
    region_names.append(region_name)

# Assign the list as a new column in the dataframe
df['region_names'] = region_names

# Display the updated DataFram
#df1.drop(['region_name'], axis=1)
df

,DateTime,City,Facility,Device,Desk,Operator,WaitTime,ConversationTime,Reason,ReasonEnteredByUser,Flag_BarrierOpened,WaitTimeSeconds,Convo_Time,region_names
0,2023-07-15 06:02:52.727,Eindhoven,Eindhoven Veemgebouw,EI/VE/IN ABBO,9926,Qais Shirzai,0 days 02:05:34.870000,00:00:02.040000,No reason entered,-,-,7534.870,0 days 00:00:02.040000,Noord-Brabant
1,2023-07-15 06:05:15.100,Breda,Breda De Prins,BR/DP/UIT-2,9926,Qais Shirzai,0 days 02:03:16.037000,00:00:01.633000,No reason entered,-,-,7396.037,0 days 00:00:01.633000,Noord-Brabant
2,2023-07-15 06:10:21.567,Breda,Breda De Prins,BR/DP/BA-1,9926,Qais Shirzai,0 days 01:58:14.226000,00:00:01.030000,No reason entered,-,-,7094.226,0 days 00:00:01.030000,Noord-Brabant
3,2023-07-15 06:10:19.817,Breda,Breda De Prins,BR/DP/BA-3,9926,Qais Shirzai,0 days 01:58:14.013000,00:00:01,No reason entered,-,-,7094.013,0 days 00:00:01,Noord-Brabant
4,2023-07-15 06:13:13.130,Breda,Breda De Prins,BR/DP/DL-2,9926,Qais Shirzai,0 days 01:55:24.383000,00:00:01.380000,No reason entered,-,-,6924.383,0 days 00:00:01.380000,Noord-Brabant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433969,2022-11-27 11:38:34.457,-,-,VB/AK/UIT-1,-,-,NaT,-,-,-,1,NaN,NaT,None
433970,2023-09-28 17:45:21.910,-,-,VB/AK/UIT-2,-,-,NaT,-,-,-,1,NaN,NaT,None
433971,2023-09-28 20:16:15.523,-,-,VB/AK/UIT-2,-,-,NaT,-,-,-,1,NaN,NaT,None
433972,2023-06-03 11:44:34.517,-,-,WE/UR/DL,-,-,NaT,-,-,-,1,NaN,NaT,None
433973,2023-06-29 14:14:42.440,-,-,ZA/EB/UIT-1 NP,-,-,NaT,-,-,-,-,NaN,NaT,None

In [28]:
import pandas as pd
df1= pd.read_csv('80305ned_UntypedDataSet_29112023_120005.csv', delimiter = ';')
df1

,ID,RegioS,Perioden,AfstandTotHuisartsenpraktijk_1,Binnen1Km_2,Binnen3Km_3,Binnen5Km_4,AfstandTotHuisartsenpost_5,AfstandTotApotheek_6,AfstandTotZiekenhuis_7,...,Binnen5Km_116,Binnen10Km_117,Binnen20Km_118,AfstandTotSauna_119,AfstandTotZonnebank_120,AfstandTotAttractie_121,Binnen10Km_122,Binnen20Km_123,Binnen50Km_124,AfstandTotBrandweerkazerne_125
0,133,PV22,2020JJ00,1.6,0.7,2.5,4.5,7.6,1.8,7.7,...,0.4,0.7,1.9,10.4,8.0,5.4,1.8,5.8,30.0,3.1
1,134,PV22,2021JJ00,1.7,0.7,2.5,4.4,7.7,1.8,7.8,...,0.4,0.7,1.9,10.5,8.1,5.3,1.9,6.0,31.1,3.1
2,135,PV22,2022JJ00,1.7,0.7,2.4,4.4,7.8,2.0,7.7,...,0.4,0.7,2.0,11.3,8.2,5.5,1.8,5.6,29.2,3.1
3,150,PV23,2020JJ00,1.2,1.1,5.5,9.9,7.6,1.4,5.1,...,0.7,1.3,3.0,12.6,3.9,6.1,1.8,5.9,26.9,2.2
4,151,PV23,2021JJ00,1.2,1.0,5.4,9.6,8.9,1.4,5.1,...,0.6,1.2,2.8,12.6,4.0,6.0,2.1,6.2,29.2,2.3
5,152,PV23,2022JJ00,1.3,0.9,5.1,9.1,9.0,1.4,5.4,...,0.6,1.1,2.7,11.9,4.1,7.0,2.0,6.1,29.0,2.3
6,167,PV24,2020JJ00,1.3,0.8,4.7,8.9,5.2,1.4,4.9,...,0.3,0.5,1.6,10.4,3.9,7.6,2.5,4.1,29.7,2.7
7,168,PV24,2021JJ00,1.3,0.8,4.5,8.7,5.4,1.5,5.0,...,0.3,0.5,1.5,11.0,4.7,6.1,2.0,3.8,35.4,2.7
8,169,PV24,2022JJ00,1.3,0.8,4.5,8.8,5.5,1.6,4.5,...,0.3,0.5,1.5,16.4,4.8,6.2,2.0,3.8,36.7,2.9
9,184,PV25,2020JJ00,1.1,1.0,4.4,8.3,7.6,1.4,5.3,...,0.8,2.0,5.5,9.2,4.2,6.1,1.8,4.7,31.4,2.0
10,185,PV25,2021JJ00,1.2,1.0,4.3,8.2,7.7,1.4,5.3,...,0.7,1.8,5.0,8.3,4.4,5.9,1.9,5.4,35.7,2.0
11,186,PV25,2022JJ00,1.2,0.9,4.2,8.1,8.4,1.4,5.4,...,0.6,1.6,4.5,8.1,4.4,5.6,1.9,5.4,35.3,2.1
12,201,PV26,2020JJ00,0.9,1.4,7.4,15.2,6.7,1.0,3.8,...,1.7,3.9,9.3,8.0,2.8,5.3,2.4,7.5,49.0,1.8
13,202,PV26,2021JJ00,0.9,1.3,7.4,15.2,6.8,1.0,3.8,...,1.5,3.5,8.6,7.4,2.8,5.2,2.5,8.6,58.0,1.8
14,203,PV26,2022JJ00,1.0,1.2,6.9,14.5,7.0,1.1,3.9,...,1.4,3.3,8.4,6.4,2.9,4.9,3.0,9.5,57.3,1.9
15,218,PV27,2020JJ00,0.8,2.3,15.6,33.6,5.0,1.0,3.7,...,2.4,5.3,11.8,5.8,2.6,4.4,3.4,9.8,47.2,1.9
16,219,PV27,2021JJ00,0.8,2.3,15.2,32.7,5.0,1.0,3.6,...,2.4,5.4,12.2,4.9,2.6,3.8,4.4,13.1,57.1,1.9
17,220,PV27,2022JJ00,0.8,1.8,13.8,31.2,5.1,1.1,3.8,...,2.3,5.3,11.9,4.9,2.8,4.0,4.3,12.9,56.9,2.0
18,235,PV28,2020JJ00,0.8,2.1,12.5,28.7,4.8,0.9,3.3,...,1.8,4.2,11.9,6.3,2.4,4.4,5.2,15.3,54.0,1.9
19,236,PV28,2021JJ00,0.8,2.0,12.3,28.2,4.8,0.9,3.2,...,1.7,4.1,11.6,5.7,2.4,4.0,5.8,17.3,64.6,1.9
20,237,PV28,2022JJ00,0.8,1.7,11.4,27.0,5.2,1.0,3.4,...,1.8,4.3,12.1,6.0,2.6,4.2,5.6,16.6,63.0,2.0
21,269,PV30,2020JJ00,1.0,1.1,5.8,11.6,6.7,1.4,5.1,...,0.9,2.0,5.2,7.0,3.9,6.5,2.2,6.2,30.4,2.0
22,270,PV30,2021JJ00,1.0,1.1,5.7,11.4,6.7,1.4,5.2,...,1.0,2.0,5.0,6.8,3.9,5.3,2.9,8.4,39.8,2.0
23,271,PV30,2022JJ00,1.1,1.0,5.5,11.2,6.8,1.3,5.3,...,0.9,1.9,4.9,7.0,4.0,5.3,2.7,8.0,38.9,2.2
24,286,PV31,2020JJ00,1.0,1.1,4.9,10.0,6.7,1.5,4.6,...,1.0,2.0,4.4,7.2,3.7,6.4,2.1,5.7,17.1,2.4
25,287,PV31,2021JJ00,1.0,1.1,4.8,9.9,6.7,1.5,4.6,...,1.0,2.0,4.6,8.2,3.7,5.2,2.7,7.4,23.7,2.5
26,288,PV31,2022JJ00,1.1,1.0,4.6,9.6,7.7,1.5,4.6,...,1.1,2.1,4.7,10.3,3.9,5.3,2.5,7.1,22.3,2.7

In [21]:
df1['RegioS']

0     PV22
1     PV22
2     PV22
3     PV23
4     PV23
5     PV23
6     PV24
7     PV24
8     PV24
9     PV25
10    PV25
11    PV25
12    PV26
13    PV26
14    PV26
15    PV27
16    PV27
17    PV27
18    PV28
19    PV28
20    PV28
21    PV30
22    PV30
23    PV30
24    PV31
25    PV31
26    PV31
Name: RegioS, dtype: object

In [22]:
dict_1= {'PV22':'Drenthe', 'PV23':'Overijssel', 'PV24':'Flevoland', 'PV25':'Gelderland', 'PV26':'Utrecht','PV27':'Noord-Holland', 'PV28':'Zuid-Holland','PV30':'Noord-Brabant', 'PV31':'Limburg'}
dict_1

{'PV22': 'Drenthe',
 'PV23': 'Overijssel',
 'PV24': 'Flevoland',
 'PV25': 'Gelderland',
 'PV26': 'Utrecht',
 'PV27': 'Noord-Holland',
 'PV28': 'Zuid-Holland',
 'PV30': 'Noord-Brabant',
 'PV31': 'Limburg'}

In [29]:
df1['RegioS'] = df1['RegioS'].str.strip()
region_names = []

# Iterate over each row in the dataframe
for index, row in df1.iterrows():
    region_code = row['RegioS']
    # Find the corresponding region name in the dictionary
    region_name = dict_1.get(region_code, None)  # Returns None if not found
    # Append the region name to the list
    region_names.append(region_name)

# Assign the list as a new column in the dataframe
df1['region_names'] = region_names

# Display the updated DataFram
#df1.drop(['region_name'], axis=1)

In [30]:
df2= pd.read_csv('Mobility.csv', delimiter = ';')
df2

,ID,TravelMotives,Population,TravelModes,Margins,RegionCharacteristics,Periods,Trips_1,DistanceTravelled_2,TimeTravelled_3,Trips_4,DistanceTravelled_5,TimeTravelled_6
0,367,T001080,A048710,A048583,MW00000,PV22,2020JJ00,0.94,14.45,19.68,345,5287,120.1
1,368,T001080,A048710,A048583,MW00000,PV22,2021JJ00,0.96,16.05,21.95,351,5859,133.5
2,369,T001080,A048710,A048583,MW00000,PV22,2022JJ00,1.05,18.22,24.48,383,6649,148.9
3,372,T001080,A048710,A048583,MW00000,PV23,2020JJ00,0.87,14.10,20.00,319,5160,122.0
4,373,T001080,A048710,A048583,MW00000,PV23,2021JJ00,0.90,15.32,21.23,327,5591,129.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,51118,2030250,A048709,A048584,MBG0095,PV30,2021JJ00,0.03,0.40,0.58,12,145,3.6
3236,51119,2030250,A048709,A048584,MBG0095,PV30,2022JJ00,0.04,0.65,0.92,13,236,5.6
3237,51122,2030250,A048709,A048584,MBG0095,PV31,2020JJ00,0.03,.,.,11,.,.
3238,51123,2030250,A048709,A048584,MBG0095,PV31,2021JJ00,0.04,.,0.97,13,.,5.9
3239,51124,2030250,A048709,A048584,MBG0095,PV31,2022JJ00,0.04,.,1.39,14,.,8.5

In [31]:
df2['RegionCharacteristics'] = df2['RegionCharacteristics'].str.strip()
region_names = []

# Iterate over each row in the dataframe
for index, row in df2.iterrows():
    region_code = row['RegionCharacteristics']
    # Find the corresponding region name in the dictionary
    region_name = dict_1.get(region_code, None)  # Returns None if not found
    # Append the region name to the list
    region_names.append(region_name)

# Assign the list as a new column in the dataframe
df2['region_names'] = region_names
df2

,ID,TravelMotives,Population,TravelModes,Margins,RegionCharacteristics,Periods,Trips_1,DistanceTravelled_2,TimeTravelled_3,Trips_4,DistanceTravelled_5,TimeTravelled_6,region_names
0,367,T001080,A048710,A048583,MW00000,PV22,2020JJ00,0.94,14.45,19.68,345,5287,120.1,Drenthe
1,368,T001080,A048710,A048583,MW00000,PV22,2021JJ00,0.96,16.05,21.95,351,5859,133.5,Drenthe
2,369,T001080,A048710,A048583,MW00000,PV22,2022JJ00,1.05,18.22,24.48,383,6649,148.9,Drenthe
3,372,T001080,A048710,A048583,MW00000,PV23,2020JJ00,0.87,14.10,20.00,319,5160,122.0,Overijssel
4,373,T001080,A048710,A048583,MW00000,PV23,2021JJ00,0.90,15.32,21.23,327,5591,129.2,Overijssel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,51118,2030250,A048709,A048584,MBG0095,PV30,2021JJ00,0.03,0.40,0.58,12,145,3.6,Noord-Brabant
3236,51119,2030250,A048709,A048584,MBG0095,PV30,2022JJ00,0.04,0.65,0.92,13,236,5.6,Noord-Brabant
3237,51122,2030250,A048709,A048584,MBG0095,PV31,2020JJ00,0.03,.,.,11,.,.,Limburg
3238,51123,2030250,A048709,A048584,MBG0095,PV31,2021JJ00,0.04,.,0.97,13,.,5.9,Limburg
3239,51124,2030250,A048709,A048584,MBG0095,PV31,2022JJ00,0.04,.,1.39,14,.,8.5,Limburg

In [33]:
df=df.merge(df1, on ='region_names' , how= 'left')

df
#it's not working even for the first data now even though it did before

MemoryError: Unable to allocate 2.68 GiB for an array with shape (92, 3904982) and data type float64